# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EofVar <- function(ObsTrack, Pred, C, usecores, verbose) {
    .Call(`_RLT_EofVar`, ObsTrack, Pred, C, usecores, verbose)
}

ARMA_EMPTY_UMAT <- function() {
    .Call(`_RLT_ARMA_EMPTY_UMAT`)
}

ARMA_EMPTY_VEC <- function() {
    .Call(`_RLT_ARMA_EMPTY_VEC`)
}

RegUniForestFit <- function(X, Y, Ncat, obsweight, varweight, ObsTrack, param) {
    .Call(`_RLT_RegUniForestFit`, X, Y, Ncat, obsweight, varweight, ObsTrack, param)
}

RegUniForestPred <- function(SplitVar, SplitValue, LeftNode, RightNode, NodeAve, X, Ncat, treeindex, keep_all, usecores, verbose) {
    .Call(`_RLT_RegUniForestPred`, SplitVar, SplitValue, LeftNode, RightNode, NodeAve, X, Ncat, treeindex, keep_all, usecores, verbose)
}

